export const  PLACE_ORDER_REQUEST="PLACE_ORDER_REQUEST";
export const  PLACE_ORDER_SUCCESS="PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_FAIL = "PLACE_ORDER_FAIL";
export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAIL = "GET_ORDER_FAIL";
export const CANCEL_PLACEORDER = "CANCEL_PLACEORDER";
export const RESET_ORDER = "RESET_ORDER";