export const  CHOOSE_PACKAGE_REQUEST= "CHOOSE_PACKAGE_REQUEST";
export const  CHOOSE_PACKAGE_SUCCESS= "CHOOSE_PACKAGE_SUCCESS";
export const  CHOOSE_PACKAGE_FAIL= "CHOOSE_PACKAGE_FAIL";
export const  CHOOSE_PACKAGE_RESET= "CHOOSE_PACKAGE_RESET";