export const GET_PRODUCTS_REQUEST="GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS="GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL="GET_PRODUCTS_FAIL";
export const SINGLE_PRODUCT_REQUEST="SINGLE_PRODUCT_REQUEST";
export const SINGLE_PRODUCT_SUCCESS="SINGLE_PRODUCT_SUCCESS";
export const SINGLE_PRODUCT_FAIL="SINGLE_PRODUCT_FAIL";